[package]
name = "script-wizard"
version = "0.1.22"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
clap = { version = "4.3.23", features = ["derive", "env"] }
inquire = { git="https://github.com/EnigmaCurry/inquire.git", branch="script-wizard", features = ["date", "editor"]}
serde_json = "1.0.107"
